# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49b0ba5b624d455be0cc6eadfc493bf22f33fb7a487518edaa31442c423848bd53cb259cb0a57c2669875bc2b420786a963a6c5e65b64dbc8eceec562d6edd35

test:
  secret_key_base: f7b7e0418b4e02a875c6488b3e39b2a05818b513107a17bd10f4f80b2bb09a45f30e9a87b48bef443c7bb7a6cf5cc025bf75b57759e562176e595bba92bbf70a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
